### ISSUE TITLE
Question: Close Buffer with `<esc>`

### ISSUE THREAD

**Issue by harrisoncramer** [AckslD/messages.nvim#15]
Hello! Thanks so much for building this.

Would it be possible to name the messages buffer, or provide some sort of identifying information?

I'd love to be able to hit `<esc>` to close it, but I'm not seeing it in the `:buffers` call and not sure how to target it with a lua function. Apologies if this isn't in scope. Thanks!

**Comment by hehelego** [comment]
Change the `prepare_buffer` function in your `messages.nvim` config:

```lua
prepare_buffer = function(opts)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.keymap.set('n', '<Esc>', '<cmd>close<cr>', {buffer = buf})
  return vim.api.nvim_open_win(buf, true, opts)
end,
```

----------------

You also may want to try this patch #14 , it allows you specify buffer options (filetype, number column, syntax highlinghting, etc.).  

The following lua code maps `q` to `:close<cr>` for `messages.nvim` message capture buffers.

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "messages" },
	callback = function(args)
		vim.keymap.set("n", "q", "<cmd>close<cr>",
          { silent = false, noremap = true, buffer = args.buf, }
        )
	end,
})
```

**Comment by harrisoncramer** [comment]
First route worked like a charm, thank you!

**Comment by AckslD** [comment]
Thanks @hehelego and glad to hear it works now @harrisoncramer
