### ISSUE TITLE
Allow customizing command name

### ISSUE THREAD

**Issue by smjonas** [AckslD/messages.nvim#3]
Hey, today I thought that it would be nice to have a toggleable `:messages` command, then I found your brand-new plugin :D Thanks for creating it.

I know this is still WIP but would you consider adding an option for the command name? So that one could type e.g. `:Mes messages` instead of `:Messages messages`?

Edit: I also just noticed that one can't really toggle the messages window yet, what do you think about adding a `:TogglesMessages` command that either closes or opens the messages window?

**Comment by AckslD** [comment]
Hi @smjonas, should be done by #6.

Re the edit maybe we can use #5 for this discussion?

**Comment by smjonas** [comment]
Thanks! Yes #5 sounds like what I had in mind as well.
