### ISSUE TITLE
Changing default config buffer_opts requires messages.utils

### ISSUE THREAD

**Issue by dsully** [AckslD/messages.nvim#4]
Hi - thanks for the plugin! I'm trying to change the window border style, but in the `buffer_opts` function, the return map calls `clip_val`, which means I need to import `messages.utils` in order to use it.

Perhaps a slight restructuring of the config such that window styles can be separated out?

**Comment by AckslD** [comment]
I'm not sure I understand why that's an issue? Currently the `buffer_opts` uses the tiny function in `utils` to determine the floating window size. Are you worried about loading time?

**Comment by dsully** [comment]
No, not worried about loading time. Just that in order to change a single value (border from "rounded" to "single"), I need to copy the entire function into my config.

**Comment by AckslD** [comment]
I see, I'd be fine with moving the static values to separate settings which can be used by the callback. But I think it's still nice to have the callback for the user to make these decisions dynamically.
